### ISSUE TITLE
看了论文和代码想问一下，这实际上是一个关系分类的模型吗

### ISSUE THREAD

**Issue by xuanzebi** [Cartus/AGGCN_TACRED#11]
semeval-10 和 TACRED这两个数据集是不是在验证集和测试集上都给定了实体对，然后预测该实体对的关系类别吗

所以这个模型不能直接给一句话，然后直接预测包含的实体对和关系吧...

**Comment by Cartus** [comment]
Yes, if you have accessed to these two dataset, you can see that entities are given. 

You can also jointly predict entities and their corresponding relations. For example, you can go through this paper: End-to-End Relation Extraction using LSTMs on Sequences and Tree Structures[(https://www.aclweb.org/anthology/P16-1105)]

Their model also detects entities.

**Comment by xuanzebi** [comment]
Thank you very much~~
