### ISSUE TITLE
Questions about the updated results

### ISSUE THREAD

**Issue by zzysay** [Cartus/AGGCN_TACRED#12]
Hi, In the issue 7, you said that
"For the mean and std of F1 score in my experiments, the stats is 68.2% +- 0.5%.  Also, we will update this score on our paper, for a fair an concrete comparison to other methods."

However,  In the final version of ACL19 and the latest version in arxiv, the F1 score on TACRED are both 69.0. **May I ask where the latest results were released?**

**Comment by imnujf** [comment]
> Hi, In the issue 7, you said that
> "For the mean and std of F1 score in my experiments, the stats is 68.2% +- 0.5%. Also, we will update this score on our paper, for a fair an concrete comparison to other methods."
> 
> However, In the final version of ACL19 and the latest version in arxiv, the F1 score on TACRED are both 69.0. **May I ask where the latest results were released?**

How do you get 68.2% +- 0.5% ??????? Only 67.5% in my experiment!!!!!! Could you help me? My email address is imnujf@163.com. Thanks a lot.

**Comment by marchbnr** [comment]
> > Hi, In the issue 7, you said that
> > "For the mean and std of F1 score in my experiments, the stats is 68.2% +- 0.5%. Also, we will update this score on our paper, for a fair an concrete comparison to other methods."
> > However, In the final version of ACL19 and the latest version in arxiv, the F1 score on TACRED are both 69.0. **May I ask where the latest results were released?**
> 
> How do you get 68.2% +- 0.5% ??????? Only 67.5% in my experiment!!!!!! Could you help me? My email address is [imnujf@163.com](mailto:imnujf@163.com). Thanks a lot.

I get similar results:
P: 71.64 +-0.74, R: 63.55 +-0.53, F1: 67.35 +-0.44

**Comment by Cartus** [comment]
Hi @zzysay,

We updated the mean result from 5 independent runs in the latest version on arxiv and the ACL oral. The latest version on arxiv should be available soon. For the ACL version, we report the result of the pretrained model we released here. We cannot modify that version since the camera ready period passed.

**Comment by Cartus** [comment]
Hi @imnujf 

I guess you have the same issue here: https://github.com/Cartus/AGGCN_TACRED/issues/7
