### ISSUE TITLE
About case study and attention visualization mentioned in paper

### ISSUE THREAD

**Issue by DreamInvoker** [Cartus/AGGCN_TACRED#13]
hello, @Cartus ,Thanks for your wonderful work! Do you have the case study and attention visualization mentioned in your paper, I think that it's useful for me to analyse the model.

> Case study and attention visualization of this example are provided in the supplementary material

Appreciate that If you could make it available, Thanks in advance!

**Comment by Cartus** [comment]
Hi, @DreamInvoker 

Thanks for your interest in our work. As I mentioned in another repo (DCGCN), I am kind of stuck in visa stuff. I will first fix the problem you indicated in the DCGCN repo, then I will update this one.

For the DCGCN repo, it should be finished in this week.

**Comment by DreamInvoker** [comment]
@Cartus Hard work, thank you~

**Comment by Cartus** [comment]
Hi @DreamInvoker,

I have updated the paper (included all additional analyses) and uploaded it to the arXiv. It should be available in these few days.

**Comment by DreamInvoker** [comment]
Great Thanks！

**Comment by DreamInvoker** [comment]
@Cartus Great Thanks!
