### ISSUE TITLE
h_out's dimension problem ??

### ISSUE THREAD

**Issue by antxyz** [Cartus/AGGCN_TACRED#14]
As you mentioned in your paper, h_out belongs to d * N. Shouldn't he belong to (d * n) * n?

**Comment by Cartus** [comment]
Hi @antxyz ,

I am a little bit lost... Could you explain more about your question?

**Comment by antxyz** [comment]
![image](https://user-images.githubusercontent.com/54270073/66561497-2d54ed00-eb8c-11e9-90ba-4c00d386d2ba.png)
In your AGGCN article, blocks are composed of attention guide layer, dense connection layer and linear combination layer. I want to know whether the dimension of input h_out={h1, h2,..., hn} of linear combination layer is d*N or (d*N)*N？

**Comment by Cartus** [comment]
I see. The input is d x N. 

d is the input dimension of the densely connected layer. You can assume the densely connected layer is a black box. The output dimension of the black box is still d, no matter what the calculation happened inside the box.

Assume you have N different adjacency matrices generated by the attention guided layer. Then you have N different GCNs (densely connected and parameters are not shared) to encode them.

We want to have 1 final representation. Therefore, we simply convert these N outputs (each one has dimension d) into 1 by using a linear transformation.

**Comment by antxyz** [comment]
I got it. Thank you very much.
