### ISSUE TITLE
Dependency type

### ISSUE THREAD

**Issue by wt123u** [Cartus/AGGCN_TACRED#15]
Hi @Cartus 
Thank you very much for your sharing. I would like to ask whether the dependency type information is used or whether only the edge between the nodes is considered and the specific edge type is not considered?

**Comment by Cartus** [comment]
Hi @wt123u,

Yes. The edge type is not considered in this model. In this work, we only make use of the connection information (i.e. which two tokens are connected). 

Other GNN models considered the edge types (N-ary Relation Extraction using Graph State LSTM, Song, et al 2018). What they did is basically concatenate the edge embedding to the node embedding during the information propagation process. You can check their code and paper.

**Comment by wt123u** [comment]
Hi @Cartus
Thanks so much for your prompt reply. I will see Graph State LSTM soon.
