### ISSUE TITLE
Dependency information of SemEval 2010 Task8

### ISSUE THREAD

**Issue by shiningliang** [Cartus/AGGCN_TACRED#16]
Thank you for your sharing. We are very fortunate to have such a responsible author. Before you release the code for SemEval 2010 Task8, I want to know how you obtain the dependency information for it. By StanfordNLP?

**Comment by Cartus** [comment]
Yes, we (or the author of the datasets) use Stanford CoreNLP to get the corresponding dependency tree for TACRED, PubMed (cross-sentence n-ary re dataset) and SemEval Task 8.

I need to apologize for the delay in releasing the code for PubMed and SemEval dataset. I am occupied by the visa stuff in these few months. I will release them once I have some free time.

**Comment by shiningliang** [comment]
OK. Thank you very much. Don't worry. Focus on your visa. Good luck.
