### ISSUE TITLE
Question on SemEval2010_task8 dataset

### ISSUE THREAD

**Issue by HWZX** [Cartus/AGGCN_TACRED#3]
May I ask your parameters setting on SemEval2010_task8 dataset?
I can't get the performance on SemEval2010_task8 in the paper.
Thank you so much!

**Comment by Cartus** [comment]
Yes, the hyper-parameters are totally different from those used for TACRED. 

I will test it again and release the pretrained model and its corresponding hyper-parameters settings later. Will update you asap.
