### ISSUE TITLE
the Final Score

### ISSUE THREAD

**Issue by ZhangYi0621** [Cartus/AGGCN_TACRED#33]
hello, I ran the code you gave and got the Final Score:
Precision (micro): 74.361%
    Recall (micro): 30.617%
        F1 (micro): 43.375%
Why is there a gap with the original result?

**Comment by Cartus** [comment]
You did not provide any details of your working environment, training process, etc. There is no way for us to figure out what really happened when you trained the model. The explanation we could provide at this moment is you did not train the model successfully.

**Comment by ZhangYi0621** [comment]
> You did not provide any details of your working environment, training process, etc. There is no way for us to figure out what really happened when you trained the model. The explanation we could provide at this moment is you did not train the model successfully.

Thanks for your reply! I am a freshmen to learn this area about deep learning, I will learn more to find the exact questions.
