### ISSUE TITLE
how to preprocess the dataset

### ISSUE THREAD

**Issue by cxyccc** [Cartus/AGGCN_TACRED#34]
I would like to use AGGCN on my own dataset. Could you please kindly provide the preprocess code? Thank you!!

**Comment by Cartus** [comment]
Unfortunately, we do not have the preprocess code, as the TACRED dataset does not require any preprocessing. Preprocessing your own data into the format of TACRED should be trivial, just several lines of python codes will do.

You can refer to some previous issues, for example, [https://github.com/Cartus/AGGCN/issues/20](url)

**Comment by cxyccc** [comment]
Thank you for your help!

**Comment by skydiving94** [comment]
I am curious which POS tagging software is used to process the data. At the moment I am using the Stanford CoreNLP server, but the generated POS tags do not match with the default ones. For example, in the default one, left and right brackets are mapped to -LRB- and -RRB-. The result I got from Stanford is instead NNP. 

I also noticed that in the file constant.py, for POS_TO_ID, there are various tags such as "$" and "#". I am wondering which POS tagger produces those tags? Thanks for your help!

**Comment by Cartus** [comment]
Hi, we used the TACRED dataset from this paper: https://nlp.stanford.edu/pubs/zhang2017tacred.pdf, which claimed that they used Stanford CoreNLP (Manning et al., 2014) to obtain the POS and NER annotations. We simply used the POS and NER included in the dataset, so I do not know about the process to get them.

**Comment by skydiving94** [comment]
Got it. Thanks
