### ISSUE TITLE
Why did you configure the first densely connected layer with GraphConvLayer?

### ISSUE THREAD

**Issue by jeongwonkwak** [Cartus/AGGCN_TACRED#36]
hello :) I ran the code you gave but I would like to ask you why you constructed the first densely connected layer (layers[0]) with GraphConvLayer. 
The other layers(layers[1], ..., layers[N-1]) were configured with MultiGraphConvLayer, right? 
please let me know any mistake. Thank you !

**Comment by Cartus** [comment]
Hi, you are right.
The reason is that the first densely connected layer takes the dependency tree as the input (we only have one graph). For the latter layer, we constructed multiple graphs based on the node representations. That is the reason why they were configured with MultiGraphConvLayer.
