### ISSUE TITLE
适用于中文数据集吗？

### ISSUE THREAD

**Issue by nlper01** [Cartus/AGGCN_TACRED#41]
您好，
注意到论文中的实验都是在英文语料上完成的，我现在想应用到中文语料上，对于中文如何构造邻接矩阵，您有什么建议吗？
我的数据集示例如下：
`{
  "doc_id": "1",
  "paragraphs": [
    {
      "paragraph_id": "0",
      "paragraph": "中国成人2型糖尿病胰岛素促泌剂应用的专家共识",
      "sentences": [
        {
          "sentence_id": "0",
          "sentence": "中国成人2型糖尿病胰岛素促泌剂应用的专家共识",
          "start_idx": 0,
          "end_idx": 22,
          "entities": [
            {
              "entity_id": "T0",
              "entity": "2型糖尿病",
              "entity_type": "Disease",
              "start_idx": 4,
              "end_idx": 9
            },
            {
              "entity_id": "T1",
              "entity": "2型",
              "entity_type": "Class",
              "start_idx": 4,
              "end_idx": 6
            },
            {
              "entity_id": "T2",
              "entity": "胰岛素促泌剂",
              "entity_type": "Drug",
              "start_idx": 9,
              "end_idx": 15
            }
          ],
          "relations": [
            {
              "relation_type": "Drug_Disease",
              "relation_id": "R0",
              "head_entity_id": "T2",
              "tail_entity_id": "T0"
            },
            {
              "relation_type": "Class_Disease",
              "relation_id": "R1",
              "head_entity_id": "T1",
              "tail_entity_id": "T0"
            }
          ]
        }
      ]
    }
}`

**Comment by guanxichouqu** [comment]
你好，我也在跑中文数据集，可以请教一下吗

**Comment by nlper01** [comment]
你好，我的q是2925006374，我后面把这个模型搁置了，现在才重新跑，交流一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月11日(周一) 下午3:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cartus/AGGCN] 适用于中文数据集吗？ (Issue #41)




 
你好，我也在跑中文数据集，可以请教一下吗

**Comment by nlper01** [comment]
> 你好，我也在跑中文数据集，可以请教一下吗
