### ISSUE TITLE
Code to convert SemEval2010_task8 dataset

### ISSUE THREAD

**Issue by HWZX** [Cartus/AGGCN_TACRED#5]
Sorry to bother you again, I check the data format in the code:
https://github.com/qipeng/gcn-over-pruned-trees
I have to convert SemEval2010_task8 dataset to TARCED's format, but I don't know what to fill the key _subj_type_ and _obj_type_.
May I ask what to fill this two keys?
Or May I have your code for transfering SemEval2010_task8 dataset to TARCED's format?
Thank you so much!

**Comment by Cartus** [comment]
Yes, codes for TACRED and Semeval are different due to the data format, that is the reason why we only release the codes for TACRED currently. We are merging codes for Semeval and cross-sentence n-ary relation tasks. It might take some time to finish it.
