### ISSUE TITLE
关于准确率的问题

### ISSUE THREAD

**Issue by zhouyao1124** [Cartus/AGGCN_TACRED#6]
郭哥您好，在尝试复现论文代码时，发生了一些问题，执行语句为：python3 train.py --id $SAVE_ID --seed 0 --hidden_dim 300 --lr 0.7 --rnn_hidden 300 --num_epoch 100 --pooling max  --mlp_layers 1 --num_layers 2 --pooling_l2 0.002

此时准确率均为100%且f1值均为0，详细截图如下：
![2](https://user-images.githubusercontent.com/37837161/60001276-b9eca580-9698-11e9-8a23-314231ab7560.png)
![1](https://user-images.githubusercontent.com/37837161/60001277-b9eca580-9698-11e9-9464-b0d8fb0912b8.png)
希望您在方便时候能不吝赐教，谢谢！

**Comment by Cartus** [comment]
Hi,

I think the problem lies in the fact that the training and developing set is not complete. According to your last image, only 1 batch created for the training set.
