### ISSUE TITLE
micro F1 and macro F1

### ISSUE THREAD

**Issue by HWZX** [Cartus/AGGCN_TACRED#8]
The F1 score in your paper is macro F1, but in your code you calculate the micro score.
Can you share us with the code to calculate macro F1 score?
Thank you so much!

**Comment by Cartus** [comment]
The current code of this repo is for TACRED dataset. We report micro-averaged F1 scores on this dataset as the SOTA system: https://nlp.stanford.edu/pubs/zhang2018graph.pdf

The evaluation script is borrowed from this repo: https://github.com/qipeng/gcn-over-pruned-trees, which is the official implementation of the paper mentioned above.

**Comment by Cartus** [comment]
I do have a script for evaluating macro F1 score, you can give me your email address or others. Then I can just send it to you.

**Comment by ngoqhuy** [comment]
> I do have a script for evaluating macro F1 scores. You can give me your email address or others, and I can send it to you.

Could u please send me to my email: ngohuy0702@gmail.com
