### ISSUE TITLE
Experiment on n-ary relation extraction

### ISSUE THREAD

**Issue by CHELSEA234** [Cartus/AGGCN_TACRED#9]
请问如何执行n-ary relation extraction实验的代码呢，可以给出command么？就是你们paper的table 1的结果。

非常感谢~~

**Comment by Cartus** [comment]
Hi,

The current repo is only for TACRED dataset. Since the data format of the n-ary relation extraction is totally different from the TACRED, we are trying to merging them together. It might take some time to finish it.

**Comment by CHELSEA234** [comment]
好的，非常感谢。
